"""update database

Revision ID: 5dd7430a90e9
Revises: 
Create Date: 2024-12-23 15:05:24.681857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dd7430a90e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('platform_link', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=50), nullable=True),
    sa.Column('job_link', sa.Text(), nullable=True),
    sa.Column('company', sa.String(length=120), nullable=True),
    sa.Column('company_link', sa.Text(), nullable=False),
    sa.Column('posted_on', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('salary', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('applicant', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.String(length=255), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('last_date_application', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
