"""chnage company link to null

Revision ID: 811c71a3f2f7
Revises: 51b6524bd897
Create Date: 2024-12-30 19:22:14.527803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811c71a3f2f7'
down_revision = '51b6524bd897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
