"""update database for change add opening field

Revision ID: 99043bbf7616
Revises: 596aa2b3481a
Create Date: 2024-12-23 16:37:36.900956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99043bbf7616'
down_revision = '596aa2b3481a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('opening', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'opening')
    # ### end Alembic commands ###
