"""update database for change last_dat_chnage dattime to str

Revision ID: ca843a3a794c
Revises: 5dd7430a90e9
Create Date: 2024-12-23 15:08:26.403165

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca843a3a794c'
down_revision = '5dd7430a90e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'last_date_application',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=250),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'last_date_application',
               existing_type=sa.String(length=250),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
